Repository okd-project/okd, pull requests merged in 2020-03, with the labels that each got.

#89 Add vSphere UPI with terraform
  Documentation/UPI/vSphere_terraform/README.md
  Documentation/UPI/vSphere_terraform/folder/main.tf
  Documentation/UPI/vSphere_terraform/folder/output.tf
  Documentation/UPI/vSphere_terraform/folder/variables.tf
  Documentation/UPI/vSphere_terraform/machine/main.tf
  Documentation/UPI/vSphere_terraform/machine/output.tf
  Documentation/UPI/vSphere_terraform/machine/variables.tf
  Documentation/UPI/vSphere_terraform/main.tf
  Documentation/UPI/vSphere_terraform/resource_pool/main.tf
  Documentation/UPI/vSphere_terraform/resource_pool/output.tf
  Documentation/UPI/vSphere_terraform/resource_pool/variables.tf
  Documentation/UPI/vSphere_terraform/terraform.tfvars.example
  Documentation/UPI/vSphere_terraform/variables.tf
  Documentation/UPI/vSphere_terraform/versions.tf
Labels: size/XL

#95 Fix some typos and whitespaces
  Documentation/UPI/Requirements/DNS_Bind.md
  Documentation/UPI/Requirements/LB_HAProxy.md
  Documentation/UPI/libvirt/libvirt.md
  Documentation/UPI/vSphere_terraform/README.md
  README.md
Labels: size/M

#96 Rename "Documentation" into "Guides"
  Guides/UPI/libvirt/Images/direct_kernel_boot.png
  Guides/UPI/libvirt/libvirt.md
  Guides/UPI/vSphere/Requirements/DNS_Bind.md
  Guides/UPI/vSphere/Requirements/LB_HAProxy.md
  Guides/UPI/vSphere/vSphere.md
  Guides/UPI/vSphere_terraform/README.md
  Guides/UPI/vSphere_terraform/folder/main.tf
  Guides/UPI/vSphere_terraform/folder/output.tf
  Guides/UPI/vSphere_terraform/folder/variables.tf
  Guides/UPI/vSphere_terraform/machine/main.tf
  Guides/UPI/vSphere_terraform/machine/output.tf
  Guides/UPI/vSphere_terraform/machine/variables.tf
  Guides/UPI/vSphere_terraform/main.tf
  Guides/UPI/vSphere_terraform/resource_pool/main.tf
  Guides/UPI/vSphere_terraform/resource_pool/output.tf
  Guides/UPI/vSphere_terraform/resource_pool/variables.tf
  Guides/UPI/vSphere_terraform/terraform.tfvars.example
  Guides/UPI/vSphere_terraform/variables.tf
  Guides/UPI/vSphere_terraform/versions.tf
Labels: size/S
